---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      customize:
        memory: 1024
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[multi_mysql::default]
    attributes:
