---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[mysql::client]
      - recipe[multi_mysql]
    attributes:
      multi_mysql:
        testing_password: "rootpass"
        default_package:
          distribution: "mariadb"
          version: "10.1.21"
          url: "http://ftp.utexas.edu/mariadb/mariadb-10.1.21/bintar-linux-glibc_214-x86_64/mariadb-10.1.21-linux-glibc_214-x86_64.tar.gz"
          checksum: "2352f5f98bfb2f9c3c0ffb1194e81a95f823d121336d811a6f7826a4c7e2fa16"
