---
driver:
  name: vagrant

provisioner:
  name: chef_solo

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[mysql::client]
      - recipe[multi_mysql]
    attributes:
      multi_mysql:
        default_package:
          distribution: "mariadb"
          version: "10.1.10"
          url: "http://ftp.utexas.edu/mariadb/mariadb-10.1.10/bintar-linux-glibc_214-x86_64/mariadb-10.1.10-linux-glibc_214-x86_64.tar.gz"
          checksum: "ef46b96dff94cc216cf3ae08dd97351eb5463dd3ac3057fd35268149144c0892"
        instances:
          default:
            server_root_password: "rootpass"
